stages:
  - build_hub
  - deploy_hub
  - deploy_aks
  - deploy_database

image:
  name: hashicorp/terraform:1.3.7
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

test:
  services:
    - mcr.microsoft.com/azure-cli:latest
  script:
    - az --version