stages:
  - deploy_hub
  - deploy_aks
  - deploy_database

image:
  name: hashicorp/terraform:1.3.7
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - apk update && apk upgrade
  - apk add curl bash openssl
  - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  - chmod +x ./kubectl
  - mv ./kubectl /usr/local/bin/kubectl
  - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

.az_login:
  - az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID -o none
  - az account set -s $ARM_SUBSCRIPTION_ID

create_hub_rg:
  stage: build_hub
  image: mcr.microsoft.com/azure-cli
  script:
    - bash ./build.sh